name: Python Package CI/CD

on:
  push:
    branches:
      - main

jobs:
  upload-python-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install configparser  # Install configparser explicitly

      - name: Build package
        run: |
          cd package
          python setup.py sdist bdist_wheel
          cd ..

      - name: Upload package to PyPI using username/password
        if: env.PYPI_USERNAME && env.PYPI_PASSWORD
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd package
          python -m twine upload dist/*
          cd ..

      - name: Upload package to PyPI using token
        if: ${{ secrets.PYPI_TOKEN }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          cd package
          python -m twine upload dist/*
          cd ..

  monitor-performance:
    runs-on: ubuntu-latest
    needs: upload-python-package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r environment/requirements.txt

      - name: Run performance monitoring script
        run: python package/monitor_performance.py